---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rook-lab
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/MarcusGraetsch/rook-k8s-lab
